### ISSUE TITLE
Sleeping is broken

### ISSUE THREAD

**Issue by roryclaasen** [GOGO98901/RorysMod#30]
Now that #15 is fixed you can sleep.... forever
You now can't wake up or rather the server wont make it day

**Comment by roryclaasen** [comment]
Day is set when getting out of bed

``` java
@SubscribeEvent
    public void onWakeUpEvent(PlayerWakeUpEvent event) {
        RMLog.info("waking up");
        event.entity.worldObj.getWorldInfo().setWorldTime(1000);
        if (Settings.enableStayInBed) {
            // RMLog.info("Should be in bed");
        }
    }
```

see [PlayerBedEventHandler.java](https://github.com/GOGO98901/RorysMod/blob/master/src/main/java/net/roryclaasen/rorysmod/event/PlayerBedEventHandler.java)

##### Update

The event `onWakeUpEvent` doesn't do anything other than get called and so I can not manipulate the event.... Going to use transformer or such like

**Comment by roryclaasen** [comment]
new crash log or rather it is the same error as #31 

```
[19:25:42] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking player
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:198) ~[NetworkSystem.class:?]
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118) ~[IntegratedServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752) [MinecraftServer$2.class:?]
Caused by: java.lang.NullPointerException
    at net.minecraft.entity.player.EntityPlayer.isInBed(EntityPlayer.java:1671) ~[EntityPlayer.class:?]
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:307) ~[EntityPlayer.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:330) ~[EntityPlayerMP.class:?]
    at net.minecraft.network.NetHandlerPlayServer.processPlayer(NetHandlerPlayServer.java:279) ~[NetHandlerPlayServer.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer.processPacket(C03PacketPlayer.java:37) ~[C03PacketPlayer.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.processPacket(C03PacketPlayer.java:271) ~[C03PacketPlayer$C06PacketPlayerPosLook.class:?]
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241) ~[NetworkManager.class:?]
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182) ~[NetworkSystem.class:?]
    ... 5 more
[19:25:42] [Server thread/ERROR]: This crash report has been saved to: C:\Users\gogo9_000\Documents\GitHub\Minecraft\Rorys-Mod\.\crash-reports\crash-2016-03-02_19.25.42-server.txt
[19:25:42] [Server thread/INFO]: Stopping server
[19:25:42] [Server thread/INFO]: Saving players
[19:25:42] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:displayCrashReport:388]: ---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 02/03/16 19:25
Description: Ticking player

java.lang.NullPointerException: Ticking player
    at net.minecraft.entity.player.EntityPlayer.isInBed(EntityPlayer.java:1671)
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:307)
    at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:330)
    at net.minecraft.network.NetHandlerPlayServer.processPlayer(NetHandlerPlayServer.java:279)
    at net.minecraft.network.play.client.C03PacketPlayer.processPacket(C03PacketPlayer.java:37)
    at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.processPacket(C03PacketPlayer.java:271)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraft.entity.player.EntityPlayer.isInBed(EntityPlayer.java:1671)
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:307)

-- Player being ticked --
Details:
    Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
    Entity ID: 68
    Entity Name: Player717
    Entity's Exact location: 1714.22, 23.00, -209.04
    Entity's Block location: World: (1714,23,-210), Chunk: (at 2,1,14 in 107,-14; contains blocks 1712,0,-224 to 1727,255,-209), Region: (3,-1; contains chunks 96,-32 to 127,-1, blocks 1536,0,-512 to 2047,255,-1)
    Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
    at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:330)
    at net.minecraft.network.NetHandlerPlayServer.processPlayer(NetHandlerPlayServer.java:279)
    at net.minecraft.network.play.client.C03PacketPlayer.processPacket(C03PacketPlayer.java:37)
    at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.processPacket(C03PacketPlayer.java:271)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@6c1ccd31
Stacktrace:
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 396423072 bytes (378 MB) / 669515776 bytes (638 MB) up to 1396703232 bytes (1332 MB)
    JVM Flags: 0 total; 
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 15 mods loaded, 15 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader] (forgeSrc-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge] (forgeSrc-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
    UCHIJAAAA   rorysmodcore{1.0} [Rory's Mod Core] (minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCHIJAAAA   rorysmod{$version} [Rory's Mod] (bin) 
    UCHIJAAAA   ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
    UCHIJAAAA   IC2{2.2.811-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.811-experimental.jar) 
    UCHIJAAAA   neiintegration{1.1.1} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.1.jar) 
    UCHIJAAAA   ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    UCHIJAAAA   ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
    UCHIJAAAA   ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    CoFHCore: -[1.7.10]3.0.3-303
    ThermalFoundation: -[1.7.10]1.2.0-102
    ThermalDynamics: -[1.7.10]1.1.0-161
    ThermalExpansion: -[1.7.10]4.0.3B1-218
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['Player717'/68, l='saves/Test World', x=1714.22, y=23.00, z=-209.04]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
[19:25:42] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:displayCrashReport:393]: #@!@# Game crashed! Crash report saved to: #@!@# .\crash-reports\crash-2016-03-02_19.25.42-server.txt
[19:25:42] [Client thread/INFO] [FML]: Waiting for the server to terminate/save.
[19:25:42] [Server thread/INFO]: Saving worlds
[19:25:42] [Server thread/INFO]: Saving chunks for level 'saves/Test World'/Overworld
[19:25:42] [Server thread/INFO]: Saving chunks for level 'saves/Test World'/Nether
[19:25:42] [Server thread/INFO] [FML]: Unloading dimension 0
[19:25:42] [Server thread/INFO] [FML]: Unloading dimension -1
[19:25:42] [Server thread/INFO] [FML]: Applying holder lookups
[19:25:42] [Server thread/INFO] [FML]: Holder lookups applied
[19:25:42] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[19:25:42] [Client thread/INFO] [FML]: Server terminated.
AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by roryclaasen** [comment]
Okay so when you sleep in a bed in the day the game will CTD (crash to desktop) but then when you relaunch and go back into the bed it wont let you.

**Comment by roryclaasen** [comment]
No longer crashes - well sometimes it does
